"""Add ai_photobooth_count to users

Revision ID: 65be2019201e
Revises: e3c0b4c7d8ab
Create Date: 2025-12-06 19:23:42.063111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65be2019201e'
down_revision: Union[str, Sequence[str], None] = 'e3c0b4c7d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SQLite requires batch mode for many operations
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Check if constraint exists before creating (optional, but good practice if retry)
        # For simplicity in this generated script, we just try to create it.
        # Note: SQLite doesn't support ADD CONSTRAINT well outside of batch mode (re-creation).
        batch_op.create_foreign_key(batch_op.f('fk_orders_voucher_id_vouchers'), 'vouchers', ['voucher_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('product_promos', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # defaulting to 0 for existing users
        batch_op.add_column(sa.Column('ai_photobooth_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('ai_photobooth_count')

    with op.batch_alter_table('product_promos', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_voucher_id_vouchers'), type_='foreignkey')
    # ### end Alembic commands ###
