export const categories = ["All", "Smoothies", "Juices", "Bowls", "Snacks"] as const;
export type Category = typeof categories[number];

export const menuItems = [
  {
    id: 1,
    name: "Berry Blast",
    description: "A refreshing blend of strawberries, blueberries, and raspberries with a hint of mint.",
    price: "8.50",
    calories: "240",
    color: "bg-red-500",
    category: "Smoothies" as Category,
  },
  {
    id: 2,
    name: "Green Goddess",
    description: "Kale, spinach, apple, and ginger for a healthy detox boost.",
    price: "9.00",
    calories: "180",
    color: "bg-green-500",
    category: "Smoothies" as Category,
  },
  {
    id: 3,
    name: "Tropical Paradise",
    description: "Mango, pineapple, and coconut milk blended to perfection.",
    price: "8.75",
    calories: "320",
    color: "bg-yellow-400",
    category: "Smoothies" as Category,
  },
  {
    id: 4,
    name: "Citrus Splash",
    description: "Orange, grapefruit, and lemon with a touch of honey.",
    price: "7.50",
    calories: "150",
    color: "bg-orange-400",
    category: "Juices" as Category,
  },
  {
    id: 5,
    name: "Protein Power",
    description: "Banana, peanut butter, chocolate protein powder, and almond milk.",
    price: "10.00",
    calories: "450",
    color: "bg-stone-600",
    category: "Smoothies" as Category,
  },
  {
    id: 6,
    name: "Acai Bowl",
    description: "Organic acai topped with granola, banana, and honey.",
    price: "12.00",
    calories: "380",
    color: "bg-purple-600",
    category: "Bowls" as Category,
  },
  {
    id: 7,
    name: "Apple Ginger Shot",
    description: "A zesty wellness shot with fresh apple and ginger.",
    price: "4.50",
    calories: "60",
    color: "bg-lime-500",
    category: "Juices" as Category,
  },
  {
    id: 8,
    name: "Dragon Fruit Bowl",
    description: "Vibrant dragon fruit base with fresh fruits and chia seeds.",
    price: "13.00",
    calories: "340",
    color: "bg-pink-500",
    category: "Bowls" as Category,
  },
  {
    id: 9,
    name: "Granola Bites",
    description: "Crunchy homemade granola bites with honey and nuts.",
    price: "5.00",
    calories: "180",
    color: "bg-amber-600",
    category: "Snacks" as Category,
  },
  {
    id: 10,
    name: "Carrot Orange Juice",
    description: "Fresh pressed carrot and orange juice, rich in vitamins.",
    price: "6.50",
    calories: "120",
    color: "bg-orange-500",
    category: "Juices" as Category,
  },
];

export type MenuItem = typeof menuItems[0];
